### PR TITLE
Timeseries

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Can we merge this @code-monk08?

### CODE REVIEW

**Comment by nightwarrior-xxx** [comment]
@code-monk08 Please explain what you have done here :)

**Comment by nightwarriorftw** [comment]
@code-monk08 Rebase your commits

**Comment by bymayanksingh** [comment]
should I merge it or separate branch?

**Comment by nightwarriorftw** [comment]
@code-monk08 Yes you can merge PR in a separate branch.
Also if you want to merge it in an existing branch. Save your changes somewhere in another local folder then pull from upstream (remove your changes for the time being) and then add your changes then push to an existing branch.

**Comment by bymayanksingh** [comment]
pushed data to master, closing.

**Pull request closed without merging**
