### PR TITLE
some visualization of crime data of maryland state

### PR DESCRIPTION
**Pull request by shah-aman**

### CODE REVIEW

**Comment by nightwarriorftw** [comment]
@shah-aman Awesome work :)

**Comment by tapaswenipathak** [comment]
Merge?

**Comment by nightwarriorftw** [comment]
@tapaswenipathak The visualization are awesome we can merge

**Comment by tapaswenipathak** [comment]
Go ahead, don't wait for me, if looks nice, mergetown.

**Comment by tapaswenipathak** [comment]
@shah-aman are you done w/ the remaining visualisations?

**Pull request merged**
