### PR TITLE
Django website

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Can we merge this @AymanShafi?

### CODE REVIEW

**Comment by nightwarriorftw** [comment]
@AymanShafi Attach a screenshot , how does the template/website look like.

**Comment by tapaswenipathak** [comment]
@nightwarrior-xxx is this implementation useful? Can you run and put a screenshot or we close out this pr.

**Comment by nightwarriorftw** [comment]
Okay I will run and check

**Comment by nightwarriorftw** [comment]
Updates -> Commented in the group

**Pull request closed without merging**
