### PR TITLE
Child Labour Data Notebook

### PR DESCRIPTION
**Pull request by nightwarriorftw**
Census 2001
Census 2011
Census 1971 1981
Census 1991 and 2001

@tapaswenipathak Please take a look

### CODE REVIEW

**Comment by nightwarriorftw** [comment]
@tapaswenipathak  Please take a look now

**Comment by shah-aman** [comment]
@nightwarrior-xxx  it will be very good if you create a choropleth map of india. I am working on this kind of maps for other dataset . Take a look at the maps on this website https://dhvanil.com/mapsofindia.html

**Comment by nightwarriorftw** [comment]
@shah-aman I have to do the same for Django App and I am using a choropleth map of India there.

**Comment by shah-aman** [comment]
@nightwarrior-xxx  so are you directly using d3.js on Django app then you need to create every visualization for every dataset again . if we are gonna display visualization of every dataset on website. Then why are we creating ipython notebooks

**Comment by tapaswenipathak** [comment]
On Mon, Jul 22, 2019 at 1:29 PM shah-aman <notifications@github.com> wrote:
>
> @nightwarrior-xxx so are you directly using d3.js on Django app then you need to create every visualization for every dataset. if we are gonna display visualization of every dataset on website. Then why are we creating ipython notebooks

These discussions should have happened much before, let's chat in
Slack today. I don't think you know what is the output required.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Pull request merged**
