### PR TITLE
Data information doc

### PR DESCRIPTION
**Pull request by tapaswenipathak**
@bhaskartalla what is the status of the doc, people who are doing notebook work require the doc.

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
👋

**Comment by tapaswenipathak** [comment]
Merge?

**Comment by NiharikaMessi** [comment]
[WDI_GDP Based data.zip](https://github.com/tapaswenipathak/TheLesserNumber/files/3439105/WDI_GDP.Based.data.zip)

@tapaswenipathak  As I worked on World Development Index Notebook, I feel we must add the GDP of the countries. Hence,here is the zip file containing the same.

**Comment by NiharikaMessi** [comment]
[WDI_GDP Based data.zip](https://github.com/tapaswenipathak/TheLesserNumber/files/3439112/WDI_GDP.Based.data.zip)
@tapaswenipathak  World Devlopment Index, GDP parameters data added.

**Comment by NiharikaMessi** [comment]
Heres, a document describing the Data I've collected.
[Data Description doc.txt](https://github.com/tapaswenipathak/TheLesserNumber/files/3464243/Data.Description.doc.txt)

**Comment by prateekmaj21** [comment]
This merge includes certain data on social issues.

**Pull request merged**
